version: 2
updates:
  - package-ecosystem: 'cargo'
    directory: '/rust'
    schedule:
      interval: 'weekly'
    groups:
      arrow-parquet:
        applies-to: version-updates
        patterns:
          - 'arrow*'
          - 'parquet'
      wasm-bindgen:
        applies-to: version-updates
        patterns:
          - 'web-sys'
          - 'wasm-bindgen*'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'dtolnay/rust-toolchain'
    exclude-paths:
      - '.github/workflows/release.yaml'
