version: 2
updates:
  - package-ecosystem: 'cargo'
    directory: '/rust'
    schedule:
      interval: 'weekly'
    groups:
      arrow-parquet:
        applies-to: version-updates
        patterns:
          - 'arrow*'
          - 'parquet'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
